# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fca3b073c4694318a19764f90ebbb11a528b9af29e5f0d3d82fdffe4eb313fbf1b98d92438295fc47e65f22a34b7d20d06d4b4da926ef572e405a7265a7300c

test:
  secret_key_base: 047cd51c1ced3cac7ba9414009532af398a0dab9770dba0b0212b413026a7940bee78ec38514f65ad1b51a472119d6ac2dd9f1f472c68dad92355c3b84d7d98d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
